# Generated by Django 5.1.4 on 2025-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drugs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
